apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: default
spec:
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils2
  namespace: default
spec:
  containers:
  - name: dnsutils2
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils3
  namespace: default
spec:
  containers:
  - name: dnsutils3
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent