# How do we want it implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-storage
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/tmp/"
    type: DirectoryOrCreate

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
