---
- name: instalando microk8s
  hosts: all
  become: true

  tasks:
    - name: update apt
      apt:
        update_cache: yes
        cache_valid_time: 86400
        upgrade: yes

    - name: upgrade apt
      apt:
        upgrade: dist

    - name: install k8s
      snap:
        name:
          - microk8s
        classic: yes

    - name: config user
      command: usermod -aG microk8s bss
      become: true

    - name: set alias
      lineinfile:
        path: /home/bss/.bashrc
        line: alias kubectl='microk8s kubectl'

- name: config dns master
  hosts: master_nodes
  command: microk8s enable dns
  become: true

- name: resetando k8s
  hosts: worker_nodes
  tasks:
    - name: leaving previous cluster
      command: microk8s leave
      become: true
      ignore_errors: yes

- name: coletando token
  hosts: master_nodes
  tasks:
    - name: get a new token
      shell: "microk8s add-node | grep '^Join' | cut -c17-"
      become: true
      register: result1

- name: adicionando node1
  hosts: kub2
  tasks:
    - name: add new node to master
      shell: "{{ hostvars['kub1']['result1']['stdout'] }}"
