---
- name: atualizando nodes
  hosts: nodes
  become: yes
  tasks:
    - name: install k8s
      snap:
        name:
          - microk8s
        classic: yes

    - name: config user
      command: usermod -aG microk8s vagrant

    - name: set alias
      lineinfile:
        path: /home/vagrant/.bashrc
        line: alias kubectl='microk8s kubectl'

- name: config dns master
  hosts: master_nodes
  tasks:
    - name: config dns master
      command: microk8s enable dns
      become: yes

- name: coletando token
  hosts: master
  tasks:
    - name: get a new token
      shell: "microk8s add-node | grep 'microk8s join 192' | cut -c2-"
      become: true
      register: result1

- name: adicionando node1
  hosts: node1
  tasks:
    - name: add new node to master
      shell: "{{ hostvars['master']['result1']['stdout'] }}"
      become: true

- name: coletando token
  hosts: master
  tasks:
    - name: get a new token
      shell: "microk8s add-node | grep 'microk8s join 192' | cut -c2-"
      become: true
      register: result2

- name: adicionando node2
  hosts: node2
  tasks:
    - name: add new node to master
      shell: "{{ hostvars['master']['result2']['stdout'] }}"
      become: true

- name: coletando token
  hosts: master
  tasks:
    - name: get a new token
      shell: "microk8s add-node | grep 'microk8s join 192' | cut -c2-"
      become: true
      register: result3

- name: adicionando node3
  hosts: node3
  tasks:
    - name: add new node to master
      shell: "{{ hostvars['master']['result3']['stdout'] }}"
      become: true


