Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
  end

  config.vm.define "nodemaster" do |nodemaster|
    nodemaster.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
      vb.name = "nodemaster"
    end
    nodemaster.vm.hostname = "nodemaster"
    nodemaster.vm.network "public_network", ip: "192.168.15.100"
  end

  config.vm.define "node1" do |node1|
    node1.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
      vb.name = "node1"
    end
    node1.vm.hostname = "node1"
    node1.vm.network "public_network", ip: "192.168.15.101"
  end 

  config.vm.define "node2" do |node2|
    node2.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
      vb.name = "node2"
    end
    node2.vm.hostname = "node2"
    node2.vm.network "public_network", ip: "192.168.15.102"
  end 

  config.vm.define "node3" do |node3|
    node3.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
      vb.name = "node3"
    end
    node3.vm.hostname = "node3"
    node3.vm.network "public_network", ip: "192.168.15.103"
  end   

  config.vm.define "ansible" do |ansible|
    ansible.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.name = "AnsibleVM"
    end
    ansible.vm.network "public_network", ip: "192.168.15.150"

    ansible.vm.provision "shell", path: "provisioner/ansible_vm_script.sh"

    ansible.vm.provision "update_vms", type: "ansible_local" do |ansible|
      ansible.playbook = "./provisioner/ansible_vm_updates.yml"
      ansible.inventory_path = "./provisioner/inventory.txt"
      ansible.limit = "all"
      ansible.verbose = false
      ansible.config_file="./provisioner/ansible.cfg"
    end

    ansible.vm.provision "setup_k8s", type: "ansible_local" do |ansible|
      ansible.playbook = "./provisioner/ansible_vm_playbook.yml"
      ansible.inventory_path = "./provisioner/inventory.txt"
      ansible.limit = "all"
      ansible.verbose = true
      ansible.config_file="./provisioner/ansible.cfg"
    end

  end
  
end